// Copyright (c) 2025 Cortexa LLC
// SPDX-License-Identifier: MIT

#include "cpu/m6502/opcodes_6502.h"

namespace sourcerer {
namespace cpu {
namespace m6502 {

using core::AddressingMode;

// Complete 6502/65C02 opcode table (all 256 entries)
// Format: {opcode, mnemonic, mode, size, cycles, branch, jump, call, return, illegal, 65c02_only}
const OpcodeInfo OPCODE_TABLE_6502[256] = {
    // 0x0_
    {0x00, "BRK", AddressingMode::IMPLIED, 1, 7, false, false, false, false, false, false},
    {0x01, "ORA", AddressingMode::INDEXED_INDIRECT, 2, 6, false, false, false, false, false, false},
    {0x02, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x03, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x04, "TSB", AddressingMode::ZERO_PAGE, 2, 5, false, false, false, false, false, true},
    {0x05, "ORA", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0x06, "ASL", AddressingMode::ZERO_PAGE, 2, 5, false, false, false, false, false, false},
    {0x07, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x08, "PHP", AddressingMode::IMPLIED, 1, 3, false, false, false, false, false, false},
    {0x09, "ORA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0x0A, "ASL", AddressingMode::ACCUMULATOR, 1, 2, false, false, false, false, false, false},
    {0x0B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x0C, "TSB", AddressingMode::ABSOLUTE, 3, 6, false, false, false, false, false, true},
    {0x0D, "ORA", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0x0E, "ASL", AddressingMode::ABSOLUTE, 3, 6, false, false, false, false, false, false},
    {0x0F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x1_
    {0x10, "BPL", AddressingMode::RELATIVE, 2, 2, true, false, false, false, false, false},
    {0x11, "ORA", AddressingMode::INDIRECT_INDEXED, 2, 5, false, false, false, false, false, false},
    {0x12, "ORA", AddressingMode::INDIRECT, 2, 5, false, false, false, false, false, true},
    {0x13, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x14, "TRB", AddressingMode::ZERO_PAGE, 2, 5, false, false, false, false, false, true},
    {0x15, "ORA", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0x16, "ASL", AddressingMode::ZERO_PAGE_X, 2, 6, false, false, false, false, false, false},
    {0x17, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x18, "CLC", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0x19, "ORA", AddressingMode::ABSOLUTE_Y, 3, 4, false, false, false, false, false, false},
    {0x1A, "INC", AddressingMode::ACCUMULATOR, 1, 2, false, false, false, false, false, true},
    {0x1B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x1C, "TRB", AddressingMode::ABSOLUTE, 3, 6, false, false, false, false, false, true},
    {0x1D, "ORA", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, false},
    {0x1E, "ASL", AddressingMode::ABSOLUTE_X, 3, 7, false, false, false, false, false, false},
    {0x1F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x2_
    {0x20, "JSR", AddressingMode::ABSOLUTE, 3, 6, false, false, true, false, false, false},
    {0x21, "AND", AddressingMode::INDEXED_INDIRECT, 2, 6, false, false, false, false, false, false},
    {0x22, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x23, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x24, "BIT", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0x25, "AND", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0x26, "ROL", AddressingMode::ZERO_PAGE, 2, 5, false, false, false, false, false, false},
    {0x27, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x28, "PLP", AddressingMode::IMPLIED, 1, 4, false, false, false, false, false, false},
    {0x29, "AND", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0x2A, "ROL", AddressingMode::ACCUMULATOR, 1, 2, false, false, false, false, false, false},
    {0x2B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x2C, "BIT", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0x2D, "AND", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0x2E, "ROL", AddressingMode::ABSOLUTE, 3, 6, false, false, false, false, false, false},
    {0x2F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x3_
    {0x30, "BMI", AddressingMode::RELATIVE, 2, 2, true, false, false, false, false, false},
    {0x31, "AND", AddressingMode::INDIRECT_INDEXED, 2, 5, false, false, false, false, false, false},
    {0x32, "AND", AddressingMode::INDIRECT, 2, 5, false, false, false, false, false, true},
    {0x33, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x34, "BIT", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, true},
    {0x35, "AND", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0x36, "ROL", AddressingMode::ZERO_PAGE_X, 2, 6, false, false, false, false, false, false},
    {0x37, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x38, "SEC", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0x39, "AND", AddressingMode::ABSOLUTE_Y, 3, 4, false, false, false, false, false, false},
    {0x3A, "DEC", AddressingMode::ACCUMULATOR, 1, 2, false, false, false, false, false, true},
    {0x3B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x3C, "BIT", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, true},
    {0x3D, "AND", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, false},
    {0x3E, "ROL", AddressingMode::ABSOLUTE_X, 3, 7, false, false, false, false, false, false},
    {0x3F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x4_
    {0x40, "RTI", AddressingMode::IMPLIED, 1, 6, false, false, false, true, false, false},
    {0x41, "EOR", AddressingMode::INDEXED_INDIRECT, 2, 6, false, false, false, false, false, false},
    {0x42, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x43, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x44, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x45, "EOR", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0x46, "LSR", AddressingMode::ZERO_PAGE, 2, 5, false, false, false, false, false, false},
    {0x47, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x48, "PHA", AddressingMode::IMPLIED, 1, 3, false, false, false, false, false, false},
    {0x49, "EOR", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0x4A, "LSR", AddressingMode::ACCUMULATOR, 1, 2, false, false, false, false, false, false},
    {0x4B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x4C, "JMP", AddressingMode::ABSOLUTE, 3, 3, false, true, false, false, false, false},
    {0x4D, "EOR", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0x4E, "LSR", AddressingMode::ABSOLUTE, 3, 6, false, false, false, false, false, false},
    {0x4F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x5_
    {0x50, "BVC", AddressingMode::RELATIVE, 2, 2, true, false, false, false, false, false},
    {0x51, "EOR", AddressingMode::INDIRECT_INDEXED, 2, 5, false, false, false, false, false, false},
    {0x52, "EOR", AddressingMode::INDIRECT, 2, 5, false, false, false, false, false, true},
    {0x53, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x54, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x55, "EOR", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0x56, "LSR", AddressingMode::ZERO_PAGE_X, 2, 6, false, false, false, false, false, false},
    {0x57, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x58, "CLI", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0x59, "EOR", AddressingMode::ABSOLUTE_Y, 3, 4, false, false, false, false, false, false},
    {0x5A, "PHY", AddressingMode::IMPLIED, 1, 3, false, false, false, false, false, true},
    {0x5B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x5C, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x5D, "EOR", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, false},
    {0x5E, "LSR", AddressingMode::ABSOLUTE_X, 3, 7, false, false, false, false, false, false},
    {0x5F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x6_
    {0x60, "RTS", AddressingMode::IMPLIED, 1, 6, false, false, false, true, false, false},
    {0x61, "ADC", AddressingMode::INDEXED_INDIRECT, 2, 6, false, false, false, false, false, false},
    {0x62, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x63, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x64, "STZ", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, true},
    {0x65, "ADC", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0x66, "ROR", AddressingMode::ZERO_PAGE, 2, 5, false, false, false, false, false, false},
    {0x67, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x68, "PLA", AddressingMode::IMPLIED, 1, 4, false, false, false, false, false, false},
    {0x69, "ADC", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0x6A, "ROR", AddressingMode::ACCUMULATOR, 1, 2, false, false, false, false, false, false},
    {0x6B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x6C, "JMP", AddressingMode::INDIRECT, 3, 5, false, true, false, false, false, false},
    {0x6D, "ADC", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0x6E, "ROR", AddressingMode::ABSOLUTE, 3, 6, false, false, false, false, false, false},
    {0x6F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x7_
    {0x70, "BVS", AddressingMode::RELATIVE, 2, 2, true, false, false, false, false, false},
    {0x71, "ADC", AddressingMode::INDIRECT_INDEXED, 2, 5, false, false, false, false, false, false},
    {0x72, "ADC", AddressingMode::INDIRECT, 2, 5, false, false, false, false, false, true},
    {0x73, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x74, "STZ", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, true},
    {0x75, "ADC", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0x76, "ROR", AddressingMode::ZERO_PAGE_X, 2, 6, false, false, false, false, false, false},
    {0x77, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x78, "SEI", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0x79, "ADC", AddressingMode::ABSOLUTE_Y, 3, 4, false, false, false, false, false, false},
    {0x7A, "PLY", AddressingMode::IMPLIED, 1, 4, false, false, false, false, false, true},
    {0x7B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x7C, "JMP", AddressingMode::ABSOLUTE_INDEXED_INDIRECT, 3, 6, false, true, false, false, false, true},
    {0x7D, "ADC", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, false},
    {0x7E, "ROR", AddressingMode::ABSOLUTE_X, 3, 7, false, false, false, false, false, false},
    {0x7F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x8_
    {0x80, "BRA", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, true},
    {0x81, "STA", AddressingMode::INDEXED_INDIRECT, 2, 6, false, false, false, false, false, false},
    {0x82, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x83, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x84, "STY", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0x85, "STA", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0x86, "STX", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0x87, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x88, "DEY", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0x89, "BIT", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, true},
    {0x8A, "TXA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0x8B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x8C, "STY", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0x8D, "STA", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0x8E, "STX", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0x8F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0x9_
    {0x90, "BCC", AddressingMode::RELATIVE, 2, 2, true, false, false, false, false, false},
    {0x91, "STA", AddressingMode::INDIRECT_INDEXED, 2, 6, false, false, false, false, false, false},
    {0x92, "STA", AddressingMode::INDIRECT, 2, 5, false, false, false, false, false, true},
    {0x93, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x94, "STY", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0x95, "STA", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0x96, "STX", AddressingMode::ZERO_PAGE_Y, 2, 4, false, false, false, false, false, false},
    {0x97, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x98, "TYA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0x99, "STA", AddressingMode::ABSOLUTE_Y, 3, 5, false, false, false, false, false, false},
    {0x9A, "TXS", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0x9B, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0x9C, "STZ", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, true},
    {0x9D, "STA", AddressingMode::ABSOLUTE_X, 3, 5, false, false, false, false, false, false},
    {0x9E, "STZ", AddressingMode::ABSOLUTE_X, 3, 5, false, false, false, false, false, true},
    {0x9F, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0xA_
    {0xA0, "LDY", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0xA1, "LDA", AddressingMode::INDEXED_INDIRECT, 2, 6, false, false, false, false, false, false},
    {0xA2, "LDX", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0xA3, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xA4, "LDY", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0xA5, "LDA", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0xA6, "LDX", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0xA7, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xA8, "TAY", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xA9, "LDA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0xAA, "TAX", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xAB, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xAC, "LDY", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0xAD, "LDA", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0xAE, "LDX", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0xAF, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0xB_
    {0xB0, "BCS", AddressingMode::RELATIVE, 2, 2, true, false, false, false, false, false},
    {0xB1, "LDA", AddressingMode::INDIRECT_INDEXED, 2, 5, false, false, false, false, false, false},
    {0xB2, "LDA", AddressingMode::INDIRECT, 2, 5, false, false, false, false, false, true},
    {0xB3, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xB4, "LDY", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0xB5, "LDA", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0xB6, "LDX", AddressingMode::ZERO_PAGE_Y, 2, 4, false, false, false, false, false, false},
    {0xB7, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xB8, "CLV", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xB9, "LDA", AddressingMode::ABSOLUTE_Y, 3, 4, false, false, false, false, false, false},
    {0xBA, "TSX", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xBB, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xBC, "LDY", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, false},
    {0xBD, "LDA", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, false},
    {0xBE, "LDX", AddressingMode::ABSOLUTE_Y, 3, 4, false, false, false, false, false, false},
    {0xBF, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0xC_
    {0xC0, "CPY", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0xC1, "CMP", AddressingMode::INDEXED_INDIRECT, 2, 6, false, false, false, false, false, false},
    {0xC2, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xC3, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xC4, "CPY", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0xC5, "CMP", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0xC6, "DEC", AddressingMode::ZERO_PAGE, 2, 5, false, false, false, false, false, false},
    {0xC7, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xC8, "INY", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xC9, "CMP", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0xCA, "DEX", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xCB, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xCC, "CPY", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0xCD, "CMP", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0xCE, "DEC", AddressingMode::ABSOLUTE, 3, 6, false, false, false, false, false, false},
    {0xCF, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0xD_
    {0xD0, "BNE", AddressingMode::RELATIVE, 2, 2, true, false, false, false, false, false},
    {0xD1, "CMP", AddressingMode::INDIRECT_INDEXED, 2, 5, false, false, false, false, false, false},
    {0xD2, "CMP", AddressingMode::INDIRECT, 2, 5, false, false, false, false, false, true},
    {0xD3, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xD4, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xD5, "CMP", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0xD6, "DEC", AddressingMode::ZERO_PAGE_X, 2, 6, false, false, false, false, false, false},
    {0xD7, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xD8, "CLD", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xD9, "CMP", AddressingMode::ABSOLUTE_Y, 3, 4, false, false, false, false, false, false},
    {0xDA, "PHX", AddressingMode::IMPLIED, 1, 3, false, false, false, false, false, true},
    {0xDB, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xDC, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xDD, "CMP", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, false},
    {0xDE, "DEC", AddressingMode::ABSOLUTE_X, 3, 7, false, false, false, false, false, false},
    {0xDF, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0xE_
    {0xE0, "CPX", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0xE1, "SBC", AddressingMode::INDEXED_INDIRECT, 2, 6, false, false, false, false, false, false},
    {0xE2, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xE3, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xE4, "CPX", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0xE5, "SBC", AddressingMode::ZERO_PAGE, 2, 3, false, false, false, false, false, false},
    {0xE6, "INC", AddressingMode::ZERO_PAGE, 2, 5, false, false, false, false, false, false},
    {0xE7, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xE8, "INX", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xE9, "SBC", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false},
    {0xEA, "NOP", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xEB, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xEC, "CPX", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0xED, "SBC", AddressingMode::ABSOLUTE, 3, 4, false, false, false, false, false, false},
    {0xEE, "INC", AddressingMode::ABSOLUTE, 3, 6, false, false, false, false, false, false},
    {0xEF, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},

    // 0xF_
    {0xF0, "BEQ", AddressingMode::RELATIVE, 2, 2, true, false, false, false, false, false},
    {0xF1, "SBC", AddressingMode::INDIRECT_INDEXED, 2, 5, false, false, false, false, false, false},
    {0xF2, "SBC", AddressingMode::INDIRECT, 2, 5, false, false, false, false, false, true},
    {0xF3, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xF4, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xF5, "SBC", AddressingMode::ZERO_PAGE_X, 2, 4, false, false, false, false, false, false},
    {0xF6, "INC", AddressingMode::ZERO_PAGE_X, 2, 6, false, false, false, false, false, false},
    {0xF7, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xF8, "SED", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false},
    {0xF9, "SBC", AddressingMode::ABSOLUTE_Y, 3, 4, false, false, false, false, false, false},
    {0xFA, "PLX", AddressingMode::IMPLIED, 1, 4, false, false, false, false, false, true},
    {0xFB, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xFC, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
    {0xFD, "SBC", AddressingMode::ABSOLUTE_X, 3, 4, false, false, false, false, false, false},
    {0xFE, "INC", AddressingMode::ABSOLUTE_X, 3, 7, false, false, false, false, false, false},
    {0xFF, "???", AddressingMode::IMPLIED, 1, 2, false, false, false, false, true, false},
};

const OpcodeInfo& GetOpcodeInfo(uint8_t opcode) {
  return OPCODE_TABLE_6502[opcode];
}

bool IsValidOpcode(uint8_t opcode, bool allow_65c02, bool allow_illegal) {
  const OpcodeInfo& info = OPCODE_TABLE_6502[opcode];
  if (info.is_illegal && !allow_illegal) return false;
  if (info.is_65c02_only && !allow_65c02) return false;
  return true;
}

}  // namespace m6502
}  // namespace cpu
}  // namespace sourcerer
