// Copyright (c) 2025 Cortexa LLC
// SPDX-License-Identifier: MIT

#include "cpu/m6809/opcodes_6809.h"

namespace sourcerer {
namespace cpu {
namespace m6809 {

using core::AddressingMode;

// Complete 6809 opcode table (main page, all 256 entries)
// Format: {opcode, mnemonic, mode, size, cycles, branch, jump, call, return, page2, page3, illegal}
// Note: INDEXED mode size is base; actual size determined by post-byte
// Note: mnemonic is nullptr for illegal opcodes
const OpcodeInfo6809 OPCODE_TABLE_6809[256] = {
    // 0x0_
    {0x00, "NEG", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x01, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, false, true},
    {0x02, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, false, true},
    {0x03, "COM", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x04, "LSR", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x05, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, false, true},
    {0x06, "ROR", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x07, "ASR", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x08, "ASL", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x09, "ROL", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x0A, "DEC", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x0B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, false, true},
    {0x0C, "INC", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x0D, "TST", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x0E, "JMP", AddressingMode::DIRECT, 2, 3, false, true, false, false, false, false, false},
    {0x0F, "CLR", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},

    // 0x1_ - Page 2/3 prefixes and branches
    {0x10, "PAGE2", AddressingMode::IMPLIED, 1, 0, false, false, false, false, true, false, false},
    {0x11, "PAGE3", AddressingMode::IMPLIED, 1, 0, false, false, false, false, false, true, false},
    {0x12, "NOP", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x13, "SYNC", AddressingMode::IMPLIED, 1, 4, false, false, false, false, false, false, false},
    {0x14, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x15, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x16, "LBRA", AddressingMode::RELATIVE, 3, 5, true, false, false, false, false, false, false},
    {0x17, "LBSR", AddressingMode::RELATIVE, 3, 9, false, false, true, false, false, false, false},
    {0x18, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x19, "DAA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x1A, "ORCC", AddressingMode::IMMEDIATE, 2, 3, false, false, false, false, false, false, false},
    {0x1B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x1C, "ANDCC", AddressingMode::IMMEDIATE, 2, 3, false, false, false, false, false, false, false},
    {0x1D, "SEX", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x1E, "EXG", AddressingMode::IMMEDIATE, 2, 8, false, false, false, false, false, false, false},
    {0x1F, "TFR", AddressingMode::IMMEDIATE, 2, 6, false, false, false, false, false, false, false},

    // 0x2_ - Short branches
    {0x20, "BRA", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x21, "BRN", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x22, "BHI", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x23, "BLS", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x24, "BCC", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x25, "BCS", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x26, "BNE", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x27, "BEQ", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x28, "BVC", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x29, "BVS", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x2A, "BPL", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x2B, "BMI", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x2C, "BGE", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x2D, "BLT", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x2E, "BGT", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},
    {0x2F, "BLE", AddressingMode::RELATIVE, 2, 3, true, false, false, false, false, false, false},

    // 0x3_ - Indexed addressing operations
    {0x30, "LEAX", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0x31, "LEAY", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0x32, "LEAS", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0x33, "LEAU", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0x34, "PSHS", AddressingMode::IMMEDIATE, 2, 5, false, false, false, false, false, false, false},
    {0x35, "PULS", AddressingMode::IMMEDIATE, 2, 5, false, false, false, false, false, false, false},
    {0x36, "PSHU", AddressingMode::IMMEDIATE, 2, 5, false, false, false, false, false, false, false},
    {0x37, "PULU", AddressingMode::IMMEDIATE, 2, 5, false, false, false, false, false, false, false},
    {0x38, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x39, "RTS", AddressingMode::IMPLIED, 1, 5, false, false, false, true, false, false, false},
    {0x3A, "ABX", AddressingMode::IMPLIED, 1, 3, false, false, false, false, false, false, false},
    {0x3B, "RTI", AddressingMode::IMPLIED, 1, 6, false, false, false, true, false, false, false},
    {0x3C, "CWAI", AddressingMode::IMMEDIATE, 2, 20, false, false, false, false, false, false, false},
    {0x3D, "MUL", AddressingMode::IMPLIED, 1, 11, false, false, false, false, false, false, false},
    {0x3E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x3F, "SWI", AddressingMode::IMPLIED, 1, 19, false, false, false, false, false, false, false},

    // 0x4_ - Accumulator A operations (inherent)
    {0x40, "NEGA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x41, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x42, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x43, "COMA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x44, "LSRA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x45, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x46, "RORA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x47, "ASRA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x48, "ASLA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x49, "ROLA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x4A, "DECA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x4B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x4C, "INCA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x4D, "TSTA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x4E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x4F, "CLRA", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},

    // 0x5_ - Accumulator B operations (inherent)
    {0x50, "NEGB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x51, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x52, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x53, "COMB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x54, "LSRB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x55, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x56, "RORB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x57, "ASRB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x58, "ASLB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x59, "ROLB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x5A, "DECB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x5B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x5C, "INCB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x5D, "TSTB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},
    {0x5E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x5F, "CLRB", AddressingMode::IMPLIED, 1, 2, false, false, false, false, false, false, false},

    // 0x6_ - Indexed addressing operations
    {0x60, "NEG", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x61, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x62, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x63, "COM", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x64, "LSR", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x65, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x66, "ROR", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x67, "ASR", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x68, "ASL", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x69, "ROL", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x6A, "DEC", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x6B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x6C, "INC", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x6D, "TST", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0x6E, "JMP", AddressingMode::INDEXED, 2, 3, false, true, false, false, false, false, false},
    {0x6F, "CLR", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},

    // 0x7_ - Extended addressing operations
    {0x70, "NEG", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x71, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x72, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x73, "COM", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x74, "LSR", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x75, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x76, "ROR", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x77, "ASR", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x78, "ASL", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x79, "ROL", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x7A, "DEC", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x7B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x7C, "INC", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x7D, "TST", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0x7E, "JMP", AddressingMode::EXTENDED, 3, 4, false, true, false, false, false, false, false},
    {0x7F, "CLR", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},

    // 0x8_ - Immediate addressing for A register
    {0x80, "SUBA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x81, "CMPA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x82, "SBCA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x83, "SUBD", AddressingMode::IMMEDIATE, 3, 4, false, false, false, false, false, false, false},
    {0x84, "ANDA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x85, "BITA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x86, "LDA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x87, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x88, "EORA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x89, "ADCA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x8A, "ORA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x8B, "ADDA", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0x8C, "CMPX", AddressingMode::IMMEDIATE, 3, 4, false, false, false, false, false, false, false},
    {0x8D, "BSR", AddressingMode::RELATIVE, 2, 7, false, false, true, false, false, false, false},
    {0x8E, "LDX", AddressingMode::IMMEDIATE, 3, 3, false, false, false, false, false, false, false},
    {0x8F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    // 0x9_ - Direct addressing for A register
    {0x90, "SUBA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x91, "CMPA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x92, "SBCA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x93, "SUBD", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x94, "ANDA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x95, "BITA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x96, "LDA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x97, "STA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x98, "EORA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x99, "ADCA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x9A, "ORA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x9B, "ADDA", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0x9C, "CMPX", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0x9D, "JSR", AddressingMode::DIRECT, 2, 7, false, false, true, false, false, false, false},
    {0x9E, "LDX", AddressingMode::DIRECT, 2, 5, false, false, false, false, false, false, false},
    {0x9F, "STX", AddressingMode::DIRECT, 2, 5, false, false, false, false, false, false, false},

    // 0xA_ - Indexed addressing for A register
    {0xA0, "SUBA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xA1, "CMPA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xA2, "SBCA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xA3, "SUBD", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0xA4, "ANDA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xA5, "BITA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xA6, "LDA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xA7, "STA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xA8, "EORA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xA9, "ADCA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xAA, "ORA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xAB, "ADDA", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xAC, "CMPX", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0xAD, "JSR", AddressingMode::INDEXED, 2, 7, false, false, true, false, false, false, false},
    {0xAE, "LDX", AddressingMode::INDEXED, 2, 5, false, false, false, false, false, false, false},
    {0xAF, "STX", AddressingMode::INDEXED, 2, 5, false, false, false, false, false, false, false},

    // 0xB_ - Extended addressing for A register
    {0xB0, "SUBA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xB1, "CMPA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xB2, "SBCA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xB3, "SUBD", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0xB4, "ANDA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xB5, "BITA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xB6, "LDA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xB7, "STA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xB8, "EORA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xB9, "ADCA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xBA, "ORA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xBB, "ADDA", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xBC, "CMPX", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0xBD, "JSR", AddressingMode::EXTENDED, 3, 8, false, false, true, false, false, false, false},
    {0xBE, "LDX", AddressingMode::EXTENDED, 3, 6, false, false, false, false, false, false, false},
    {0xBF, "STX", AddressingMode::EXTENDED, 3, 6, false, false, false, false, false, false, false},

    // 0xC_ - Immediate addressing for B register
    {0xC0, "SUBB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xC1, "CMPB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xC2, "SBCB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xC3, "ADDD", AddressingMode::IMMEDIATE, 3, 4, false, false, false, false, false, false, false},
    {0xC4, "ANDB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xC5, "BITB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xC6, "LDB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xC7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC8, "EORB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xC9, "ADCB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xCA, "ORB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xCB, "ADDB", AddressingMode::IMMEDIATE, 2, 2, false, false, false, false, false, false, false},
    {0xCC, "LDD", AddressingMode::IMMEDIATE, 3, 3, false, false, false, false, false, false, false},
    {0xCD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xCE, "LDU", AddressingMode::IMMEDIATE, 3, 3, false, false, false, false, false, false, false},
    {0xCF, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    // 0xD_ - Direct addressing for B register
    {0xD0, "SUBB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xD1, "CMPB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xD2, "SBCB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xD3, "ADDD", AddressingMode::DIRECT, 2, 6, false, false, false, false, false, false, false},
    {0xD4, "ANDB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xD5, "BITB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xD6, "LDB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xD7, "STB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xD8, "EORB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xD9, "ADCB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xDA, "ORB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xDB, "ADDB", AddressingMode::DIRECT, 2, 4, false, false, false, false, false, false, false},
    {0xDC, "LDD", AddressingMode::DIRECT, 2, 5, false, false, false, false, false, false, false},
    {0xDD, "STD", AddressingMode::DIRECT, 2, 5, false, false, false, false, false, false, false},
    {0xDE, "LDU", AddressingMode::DIRECT, 2, 5, false, false, false, false, false, false, false},
    {0xDF, "STU", AddressingMode::DIRECT, 2, 5, false, false, false, false, false, false, false},

    // 0xE_ - Indexed addressing for B register
    {0xE0, "SUBB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xE1, "CMPB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xE2, "SBCB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xE3, "ADDD", AddressingMode::INDEXED, 2, 6, false, false, false, false, false, false, false},
    {0xE4, "ANDB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xE5, "BITB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xE6, "LDB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xE7, "STB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xE8, "EORB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xE9, "ADCB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xEA, "ORB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xEB, "ADDB", AddressingMode::INDEXED, 2, 4, false, false, false, false, false, false, false},
    {0xEC, "LDD", AddressingMode::INDEXED, 2, 5, false, false, false, false, false, false, false},
    {0xED, "STD", AddressingMode::INDEXED, 2, 5, false, false, false, false, false, false, false},
    {0xEE, "LDU", AddressingMode::INDEXED, 2, 5, false, false, false, false, false, false, false},
    {0xEF, "STU", AddressingMode::INDEXED, 2, 5, false, false, false, false, false, false, false},

    // 0xF_ - Extended addressing for B register
    {0xF0, "SUBB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xF1, "CMPB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xF2, "SBCB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xF3, "ADDD", AddressingMode::EXTENDED, 3, 7, false, false, false, false, false, false, false},
    {0xF4, "ANDB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xF5, "BITB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xF6, "LDB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xF7, "STB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xF8, "EORB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xF9, "ADCB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xFA, "ORB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xFB, "ADDB", AddressingMode::EXTENDED, 3, 5, false, false, false, false, false, false, false},
    {0xFC, "LDD", AddressingMode::EXTENDED, 3, 6, false, false, false, false, false, false, false},
    {0xFD, "STD", AddressingMode::EXTENDED, 3, 6, false, false, false, false, false, false, false},
    {0xFE, "LDU", AddressingMode::EXTENDED, 3, 6, false, false, false, false, false, false, false},
    {0xFF, "STU", AddressingMode::EXTENDED, 3, 6, false, false, false, false, false, false, false},
};

// Page 2 opcodes ($10 prefix) - primarily long branches
// Format: {opcode, mnemonic, mode, size, cycles, branch, jump, call, return, page2, page3}
const OpcodeInfo6809 OPCODE_TABLE_6809_PAGE2[256] = {
    // Most page 2 opcodes are undefined
    {0x00, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x01, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x02, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x03, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x04, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x05, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x06, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x07, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x08, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x09, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x0A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x0B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x0C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x0D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x0E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x0F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},

    {0x10, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x11, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x12, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x13, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x14, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x15, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x16, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x17, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x18, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x19, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x1A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x1B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x1C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x1D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x1E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x1F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},

    // Long branches ($10 $2x)
    {0x20, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x21, "LBRN", AddressingMode::RELATIVE, 4, 5, false, false, false, false, true, false, false},
    {0x22, "LBHI", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x23, "LBLS", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x24, "LBCC", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x25, "LBCS", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x26, "LBNE", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x27, "LBEQ", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x28, "LBVC", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x29, "LBVS", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x2A, "LBPL", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x2B, "LBMI", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x2C, "LBGE", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x2D, "LBLT", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x2E, "LBGT", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},
    {0x2F, "LBLE", AddressingMode::RELATIVE, 4, 5, true, false, false, false, true, false, false},

    // Page 2 $3x-$7x mostly undefined
    {0x30, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x31, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x32, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x33, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x34, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x35, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x36, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x37, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x38, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x39, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x3A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x3B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x3C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x3D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x3E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x3F, "SWI2", AddressingMode::IMPLIED, 2, 20, false, false, false, false, true, false, false},

    // Fill remaining page 2 slots (0x40-0xFF) with undefined
    {0x40, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x41, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x42, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x43, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x44, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x45, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x46, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x47, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x48, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x49, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x4A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x4B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x4C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x4D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x4E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x4F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},

    {0x50, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x51, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x52, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x53, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x54, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x55, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x56, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x57, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x58, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x59, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x5A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x5B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x5C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x5D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x5E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x5F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},

    {0x60, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x61, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x62, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x63, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x64, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x65, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x66, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x67, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x68, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x69, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x6A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x6B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x6C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x6D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x6E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x6F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},

    {0x70, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x71, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x72, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x73, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x74, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x75, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x76, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x77, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x78, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x79, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x7A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x7B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x7C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x7D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x7E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x7F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},

    // Page 2 $8x-$Fx - Y register and S register operations (mirrors main page but for Y/S)
    {0x80, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x81, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x82, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x83, "CMPD", AddressingMode::IMMEDIATE, 4, 5, false, false, false, false, true, false, false},
    {0x84, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x85, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x86, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x87, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x88, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x89, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x8A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x8B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x8C, "CMPY", AddressingMode::IMMEDIATE, 4, 5, false, false, false, false, true, false, false},
    {0x8D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x8E, "LDY", AddressingMode::IMMEDIATE, 4, 4, false, false, false, false, true, false, false},
    {0x8F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},

    {0x90, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x91, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x92, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x93, "CMPD", AddressingMode::DIRECT, 3, 7, false, false, false, false, true, false, false},
    {0x94, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x95, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x96, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x97, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x98, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x99, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x9A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x9B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x9C, "CMPY", AddressingMode::DIRECT, 3, 7, false, false, false, false, true, false, false},
    {0x9D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0x9E, "LDY", AddressingMode::DIRECT, 3, 6, false, false, false, false, true, false, false},
    {0x9F, "STY", AddressingMode::DIRECT, 3, 6, false, false, false, false, true, false, false},

    {0xA0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xA1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xA2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xA3, "CMPD", AddressingMode::INDEXED, 3, 7, false, false, false, false, true, false, false},
    {0xA4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xA5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xA6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xA7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xA8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xA9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xAA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xAB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xAC, "CMPY", AddressingMode::INDEXED, 3, 7, false, false, false, false, true, false, false},
    {0xAD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xAE, "LDY", AddressingMode::INDEXED, 3, 6, false, false, false, false, true, false, false},
    {0xAF, "STY", AddressingMode::INDEXED, 3, 6, false, false, false, false, true, false, false},

    {0xB0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xB1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xB2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xB3, "CMPD", AddressingMode::EXTENDED, 4, 8, false, false, false, false, true, false, false},
    {0xB4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xB5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xB6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xB7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xB8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xB9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xBA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xBB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xBC, "CMPY", AddressingMode::EXTENDED, 4, 8, false, false, false, false, true, false, false},
    {0xBD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xBE, "LDY", AddressingMode::EXTENDED, 4, 7, false, false, false, false, true, false, false},
    {0xBF, "STY", AddressingMode::EXTENDED, 4, 7, false, false, false, false, true, false, false},

    {0xC0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC3, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xC9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xCA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xCB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xCC, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xCD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xCE, "LDS", AddressingMode::IMMEDIATE, 4, 4, false, false, false, false, true, false, false},
    {0xCF, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},

    {0xD0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD3, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xD9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xDA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xDB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xDC, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xDD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xDE, "LDS", AddressingMode::DIRECT, 3, 6, false, false, false, false, true, false, false},
    {0xDF, "STS", AddressingMode::DIRECT, 3, 6, false, false, false, false, true, false, false},

    {0xE0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE3, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xE9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xEA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xEB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xEC, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xED, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xEE, "LDS", AddressingMode::INDEXED, 3, 6, false, false, false, false, true, false, false},
    {0xEF, "STS", AddressingMode::INDEXED, 3, 6, false, false, false, false, true, false, false},

    {0xF0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF3, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xF9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xFA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xFB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xFC, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xFD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, true, false, true},
    {0xFE, "LDS", AddressingMode::EXTENDED, 4, 7, false, false, false, false, true, false, false},
    {0xFF, "STS", AddressingMode::EXTENDED, 4, 7, false, false, false, false, true, false, false},
};

// Page 3 opcodes ($11 prefix) - primarily U register operations and SWI3
// Format is similar to page 2
const OpcodeInfo6809 OPCODE_TABLE_6809_PAGE3[256] = {
    // Most page 3 opcodes are undefined, similar structure to page 2
    // Initialize all as unknown
    {0x00, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x01, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x02, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x03, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x04, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x05, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x06, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x07, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x08, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x09, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x0A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x0B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x0C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x0D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x0E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x0F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0x10, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x11, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x12, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x13, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x14, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x15, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x16, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x17, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x18, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x19, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x1A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x1B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x1C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x1D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x1E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x1F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0x20, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x21, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x22, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x23, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x24, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x25, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x26, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x27, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x28, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x29, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x2A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x2B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x2C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x2D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x2E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x2F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0x30, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x31, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x32, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x33, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x34, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x35, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x36, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x37, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x38, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x39, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x3A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x3B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x3C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x3D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x3E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x3F, "SWI3", AddressingMode::IMPLIED, 2, 20, false, false, false, false, false, true, false},

    // Rest of page 3 ($40-$FF) - U register operations similar to page 2 S register operations
    // For brevity, just mark all remaining as unknown unless specifically needed
    {0x40, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x41, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x42, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x43, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x44, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x45, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x46, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x47, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x48, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x49, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x4A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x4B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x4C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x4D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x4E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x4F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0x50, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x51, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x52, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x53, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x54, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x55, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x56, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x57, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x58, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x59, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x5A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x5B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x5C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x5D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x5E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x5F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0x60, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x61, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x62, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x63, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x64, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x65, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x66, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x67, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x68, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x69, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x6A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x6B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x6C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x6D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x6E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x6F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0x70, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x71, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x72, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x73, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x74, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x75, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x76, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x77, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x78, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x79, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x7A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x7B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x7C, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x7D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x7E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x7F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    // Page 3 $8x-$Fx - U register operations
    {0x80, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x81, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x82, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x83, "CMPU", AddressingMode::IMMEDIATE, 4, 5, false, false, false, false, false, true, false},
    {0x84, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x85, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x86, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x87, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x88, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x89, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x8A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x8B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x8C, "CMPS", AddressingMode::IMMEDIATE, 4, 5, false, false, false, false, false, true, false},
    {0x8D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x8E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x8F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0x90, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x91, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x92, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x93, "CMPU", AddressingMode::DIRECT, 3, 7, false, false, false, false, false, true, false},
    {0x94, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x95, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x96, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x97, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x98, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x99, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x9A, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x9B, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x9C, "CMPS", AddressingMode::DIRECT, 3, 7, false, false, false, false, false, true, false},
    {0x9D, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x9E, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0x9F, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0xA0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xA1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xA2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xA3, "CMPU", AddressingMode::INDEXED, 3, 7, false, false, false, false, false, true, false},
    {0xA4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xA5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xA6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xA7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xA8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xA9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xAA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xAB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xAC, "CMPS", AddressingMode::INDEXED, 3, 7, false, false, false, false, false, true, false},
    {0xAD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xAE, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xAF, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0xB0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xB1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xB2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xB3, "CMPU", AddressingMode::EXTENDED, 4, 8, false, false, false, false, false, true, false},
    {0xB4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xB5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xB6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xB7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xB8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xB9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xBA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xBB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xBC, "CMPS", AddressingMode::EXTENDED, 4, 8, false, false, false, false, false, true, false},
    {0xBD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xBE, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xBF, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0xC0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC3, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xC9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xCA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xCB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xCC, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xCD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xCE, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xCF, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0xD0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD3, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xD9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xDA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xDB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xDC, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xDD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xDE, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xDF, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0xE0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE3, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xE9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xEA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xEB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xEC, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xED, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xEE, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xEF, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},

    {0xF0, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF1, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF2, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF3, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF4, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF5, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF6, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF7, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF8, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xF9, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xFA, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xFB, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xFC, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xFD, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xFE, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
    {0xFF, nullptr, AddressingMode::UNKNOWN, 1, 0, false, false, false, false, false, true, true},
};

// Helper function to get opcode info (handles page prefixes)
const OpcodeInfo6809& GetOpcodeInfo(const uint8_t* data, size_t size,
                                    size_t* bytes_consumed) {
  if (bytes_consumed) *bytes_consumed = 1;

  if (size == 0) {
    static const OpcodeInfo6809 invalid = {
        0x00, "???", AddressingMode::UNKNOWN, 1, 0,
        false, false, false, false, false, false, true};
    return invalid;
  }

  uint8_t opcode = data[0];

  // Check for page 2 prefix ($10)
  if (opcode == 0x10 && size > 1) {
    if (bytes_consumed) *bytes_consumed = 2;
    return OPCODE_TABLE_6809_PAGE2[data[1]];
  }

  // Check for page 3 prefix ($11)
  if (opcode == 0x11 && size > 1) {
    if (bytes_consumed) *bytes_consumed = 2;
    return OPCODE_TABLE_6809_PAGE3[data[1]];
  }

  // Main page opcode
  return OPCODE_TABLE_6809[opcode];
}

// Check if opcode is valid
bool IsValidOpcode(const uint8_t* data, size_t size) {
  const OpcodeInfo6809& info = GetOpcodeInfo(data, size);
  return info.mode != AddressingMode::UNKNOWN;
}

}  // namespace m6809
}  // namespace cpu
}  // namespace sourcerer
